import { addDoc, collection, doc, getDoc, writeBatch } from 'firebase/firestore'
import { db } from '../firebase/config'

const confirmOrder = (cartItems, printOrder) => {
    
  const batch = writeBatch(db)
  const outOfStock = []
    
  cartItems.forEach((cartProducts) => {
    getDoc(doc(db, 'products', cartProducts.id))
    .then(async (documentSnapshot) => {
      const product = {...documentSnapshot.data(), id: documentSnapshot.id};
      
      if (product.stock >= cartProducts.quantity) {
        batch.update(doc(db, 'products', product.id) ,{
          stock: product.stock - cartProducts.quantity
        })
      } else if (product.stock < cartProducts.quantity) {

        cartProducts.quantity = product.stock;
        
      } else {
        outOfStock.push(product)
      }
      
      if (outOfStock.length === 0) {
        addDoc(collection(db, 'orders'), printOrder).then(({ id }) => {
                
          batch.commit().then(() => {
            alert(`Order generated by id ${id}`)
          })
        }).catch((error) => {
          console.log(`Error: ${error.message}`);
          alert(`Something it's wrong: ${error.message}`);
        })

      }
    })
  })
}
export default confirmOrder;
