import { addDoc, collection, doc, getDoc, writeBatch } from 'firebase/firestore'
import { db } from '../firebase/config'


const confirmOrder = (cartItems, printOrder) => {
    
  const batch = writeBatch(db)
  const outOfStock = []
    
  cartItems.forEach((cartProducts) => {
    getDoc(doc(db, 'products', cartProducts.id))
    .then(async (documentSnapshot) => {
      const product = {...documentSnapshot.data(), id: documentSnapshot.id};
      
      //Update cuando el stock supere la cant del carrito
      if (product.stock >= cartProducts.quantity) {
        batch.update(doc(db, 'products', product.id) ,{
          stock: product.stock - cartProducts.quantity
        })
      } else if (product.stock < cartProducts.quantity) {
        alert(`Quantity avaible is: ${product.stock}`) //la orden se hace por el total lo mismo
        
      } else {
        outOfStock.push(product)
      }
      console.log(`Out of Stock: ${outOfStock}`)
      
      if (outOfStock.length === 0) {
        addDoc(collection(db, 'orders'), printOrder).then(({ id }) => {
                
          //Commit para generar la orden => confirma la orden y actualiza stock
          batch.commit().then(() => {
            alert(`Order generated by id ${id}`)
          })
        }).catch((error) => {
          console.log(`Error: ${error.message}`);
        })

        //Si la cant del carrito es mayor que el stock, se avisa al usuario
      } else {
        let message = ''
        for (const item of outOfStock) {
          message += `${item.title}`
        }
        alert(`${message} out of stock`)
      }
    })
  })
}
export default confirmOrder;
